databases:
  - name: blog_db
    databaseName: blog_db_cm7v
    user: blog
    region: singapore

services:
  - type: web
    name: blog
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

